niches:
  ai_data_science:
    - "https://huggingface.co/blog/feed.xml"
    - "https://syncedreview.com/feed/"
    - "https://techcrunch.com/category/artificial-intelligence/feed/"
    - "https://towardsdatascience.com/feed"

  market_business_innovation:
    - "https://www.forbes.com/innovation/feed/"
    - "https://www.fastcompany.com/section/technology/rss"
    - "https://feeds.feedburner.com/venturebeat/SZYF"

  biotech_healthcare_innovation:
    - "https://www.nature.com/subjects/biotechnology.rss"
    - "https://www.genengnews.com/feed/"
    - "https://www.labiotech.eu/feed/"
    - "https://medicalxpress.com/rss-feed/"

  climate_sustainability:
    - "https://www.nature.com/subjects/climate-change.rss"
    - "https://www.carbonbrief.org/feed/"
    - "https://grist.org/feed/"
    - "https://cleantechnica.com/feed/"

  space_frontier_tech:
    - "https://www.nasa.gov/rss/dyn/breaking_news.rss"
    - "https://spacenews.com/feed/"
    - "https://www.space.com/feeds/all"
    - "https://arstechnica.com/science/space/rss"

  cybersecurity_risk:
    - "https://www.schneier.com/feed/atom/"
    - "https://krebsonsecurity.com/feed/"
    - "https://www.darkreading.com/rss.xml"
    - "https://www.cybersecuritydive.com/feeds/news/"

  science_research:
    - "https://www.sciencedaily.com/rss/top/science.xml"
    - "https://phys.org/rss-feed/"
    - "https://www.newscientist.com/feed/home/"

  fintech_digital_economy:
    - "https://www.pymnts.com/feed/"
    - "https://www.crowdfundinsider.com/feed/"

  policy_regulation:
    - "https://www.justsecurity.org/feed/"

  venture_capital_startups:
    - "https://news.crunchbase.com/feed/"
    - "https://future.a16z.com/feed/"
    - "https://tech.eu/feed/"

  supply_chain_industry:
    - "https://www.manufacturing.net/rss.xml"

  energy_cleantech:
    - "https://www.eia.gov/rss/todayinenergy.xml"
    - "https://www.renewableenergyworld.com/feed/"
    - "https://www.energymonitor.ai/feed/"
    - "https://www.pv-tech.org/feed/"

  healthcare_digital_health:
    - "https://healthtechmagazine.net/rss.xml"
    - "https://www.fiercehealthcare.com/rss/xml"
    - "https://www.medtechdive.com/feeds/news/"
    - "https://feeds.feedburner.com/beckershospitalreview"
  

timespan_days: 7               # articles from last N days
max_articles: 120              # cap to control cost/time
top_k_per_query: 6
chunk_size: 1000
chunk_overlap: 150
temperature: 0.2               # factual tone

sections:
  tldr_bullets: 5
  top_stories: 5
  quick_bites: 8
  further_reading: 8

output:
  folder: "output"
  filename_md: "latest.md"
  filename_html: "latest.html"

branding:
  title: "Weekly Insight"
  subtitle: "Curated summaries by TechMind Digest"
  author: "Mamoona Ramzan"

email:
  enabled: true
  smtp_server: "smtp.gmail.com"
  smtp_port: 465

